### ISSUE TITLE
timestampntz is not a valid type in Redshift

### ISSUE THREAD

**Issue by mplovepop** [fishtown-analytics/dbt-event-logging#1]
I received the following error while using this on Redshift:

```
Database error while running on-run-start
Encountered an error:
Database Error
  type "timestampntz" does not exist
```

`timestampntz` seems to be a Snowflake type. I think either use timestamp which is supported by both -- the default in Snowflake seems to be `timestampntz`: https://docs.snowflake.net/manuals/sql-reference/data-types-datetime.html -- or a new adapter method should be added to dbt and used here.

**Comment by clrcrl** [comment]
Closing as this uses the utils macro for current-timestamp.
