### ISSUE TITLE
does this support BigQuery?

### ISSUE THREAD

**Issue by darrenhaken** [fishtown-analytics/dbt-event-logging#13]

**Comment by drewbanin** [comment]
Hey @darrenhaken - I think this should work, but this package is probably not a good paradigm for BQ. While really _none_ of the databases that dbt supports are intended to receive many small `insert` statements, BigQuery in particular [has limits around how many times an `insert` can be run against a table in a given day](https://cloud.google.com/bigquery/quotas).

We have a [draft PR](https://github.com/fishtown-analytics/dbt-event-logging/pull/12) that will batch insert all of these stats at the end of the run - I think that might be a long-term better approach here.

**Comment by PowdyPowPow** [comment]
+1 for BQ

**Comment by clrcrl** [comment]
A reminder to myself: The v0.2.0 release introduces further problems for BQ: there is an assumption that `target.user` exists, and that's never the case for BQ users

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
