### ISSUE TITLE
Leverage results rather than individual inserts

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt-event-logging#16]
Work in progress PR: #12

### Describe the feature

Leverage the `results` object rather than writing individual inserts.

### Describe alternatives you've considered

Best version of this is:
- Build a dbt Cloud Singer tap
- Build a separate package on top of data returned by the Singer tap

### Who will this benefit?

Anyone suffering from slow insert performance due to this package (esp. BQ users)

Related to:
- #8: INSERT performance
- #13: Does this support bigquery

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
