### ISSUE TITLE
Tracking if a run uses the --full-refresh tag

### ISSUE THREAD

**Issue by DylanBaker** [fishtown-analytics/dbt-event-logging#2]
We've been using our own version of audit logging, but are planning on moving to this. One thing that is really useful for our analysis is tracking if a run uses the `--full-refresh` flag or not. For various reasons we periodically do a full refresh overnight and want to be able to exclude those runs/model builds from some of the analysis. 

I think this should be able to be done by adding a column to the tables and amending the log_audit_event macro to take flags.FULL_REFRESH? Does this make sense as a thing to do? And, if it is, I presume that its necessary to write an additional macro that moves the old schema to the new one, or is that not the right way to approach it?

**Comment by jthandy** [comment]
i think that's definitely a useful feature. I don't 100% follow what you're saying at the very end--macro that moves the old schema to the new one--but I'm in support of the overall concept here. if you're interested in submitting a PR I'd be happy to work through it with you! the table created in this package is created statically via a `create table` statement so you'd just have to update that as well to include an appropriate field.

**Comment by DylanBaker** [comment]
I wasn't massively clear. I was thinking about the use-case where someone is using it currently without the new column that would be created, and want to move to the new setup without losing the existing data. What's the best way for them to move from one to the other? And, should that be provided here?

**Comment by jthandy** [comment]
Oh I would assume that would just be an alter table add column statement...could be added in the release notes.

**Comment by DylanBaker** [comment]
Gotcha. Yeah that makes sense. I'll send over a PR in a bit!
