### ISSUE TITLE
Package version number

### ISSUE THREAD

**Issue by davehowell** [fishtown-analytics/dbt-event-logging#40]
I see the 0.4.2 tagged branch says it is version 0.3.0 in the dbt_project.yml file. 
https://github.com/fishtown-analytics/dbt-event-logging/blob/8b283c1fdc2203f860388e1cb759f5b0a2471f06/dbt_project.yml#L2

Is that version number not related to the tag version? I would assume that the bump version process would use that value as the source or also bump that value.

**Comment by jtcohen6** [comment]
Hey @davehowell, the `version` number in `dbt_project.yml` doesn't have any functional purpose :) But it has to be there, as a holdover from the early days. The actual, functional package version comes from the GitHub release tag.

We don't have an automated process in place today to bump package versions. I've tried, whenever I'm bumping the package, to remember to bump the `version` in `dbt_project.yml` as well. Sometimes I forget, sometimes it's not me. Let's get it up to date for the next one (https://github.com/fishtown-analytics/dbt-event-logging/pull/38)!

**Comment by davehowell** [comment]
Thanks for the clarification @jtcohen6 
If it has no functionality then it might be better to just remove it assuming you can also remove the reason why it needs to be there. The reason I was looking at it was just going through the process of upgrading some dbt projects to newer version and checking which version of dbt these packages supported and was just confused by that version number.
