### ISSUE TITLE
add sql server support

### ISSUE THREAD

**Issue by matsonj** [fishtown-analytics/dbt-event-logging#41]
### Add support for SQL Server
I would like to use this package with SQL server for monitoring dbt runs.

### Describe alternatives you've considered
Frankly, I would love to use snowflake but that is a constraint outside of my control. I have copied some of the code from this package and used it only as a post-hook, which with some fiddling worked fine. 

I am happy to fork this into a new repo if it is deemed that the SQL server user base is too small for this.

### Additional context
The areas I am specifically aware of that need tweaking are:

- SQL Server does not support "::" notation used in the insert statements
- SQL Server does not support "Create Table if not exists"

### Who will this benefit?
SQL server users looking to add telemetry into their dbt runs as described in this package.

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
