### ISSUE TITLE
Missing rows in audit table 

### ISSUE THREAD

**Issue by funnel-arvid** [fishtown-analytics/dbt-event-logging#47]
### Describe the bug
Several log rows are missing from the audit log table (about 50% of the dbt cloud jobs are missing). According to dbt metadata (artifacts) inserts have been done, but the rows are not in the table. 

### Steps To Reproduce
Run some dbt cloud jobs.

### Expected behavior
All invocation_ids from dbt cloud artifacts should exist in the audit logs.

### Actual behavior
Rows are missing from the table.

### System information

packages:
  - package: dbt-labs/logging
    version: 0.6.0

Standard logging (as described under Setup) for both models and snapshots in dbt_project.yml 

**Which database are you using dbt with?**
- [ ] Postgres
- [ ] Redshift
- [x] BigQuery
- [ ] Snowflake
- [ ] Other (specify: ____________)

**The output of `dbt --version`:**
1.0

### Additional context

Has been tested with both 1 thread and more threads. Only 1 thread did not solve it. (If it did solve it this would be a separate enhancement, since working with 1 thread in BigQuery is not good enough).

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
