### ISSUE TITLE
Error encountered when installing logging

### ISSUE THREAD

**Issue by hermandr** [fishtown-analytics/dbt-event-logging#51]
### Describe the bug

Encountered this error after installing logging package.
![image](https://user-images.githubusercontent.com/10177608/175274462-45bb3fae-8c1b-4225-a98e-18c0dd55a315.png)

### Steps To Reproduce

I followed instructions from [here](https://hub.getdbt.com/dbt-labs/logging/latest/).
Create packages.yml
![image](https://user-images.githubusercontent.com/10177608/175273468-d2be2c4e-3494-4c81-a3af-9878d277a85c.png)
Ran dbt deps
![image](https://user-images.githubusercontent.com/10177608/175273969-0da5b33e-2997-46f5-9430-2ff8d37540f6.png)

### Expected behavior

Should be running without error

### Actual behavior

Error encountered
![image](https://user-images.githubusercontent.com/10177608/175274535-81001bc4-59e8-4be6-8cb4-e866d4ea3bd7.png)

### System information
**How did you add this package to your project:**
```
packages:
  - package: dbt-labs/logging
    version: 0.6.0
```
Running dbt 0.21.1

**Which database are you using dbt with?**
- [ ] Postgres
- [ ] Redshift
- [ ] BigQuery
- [ ] Snowflake
- [X] Other (specify: _SQL Server 2016_)

**The output of `dbt --version`:**
```
installed version: 0.21.1
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.21.1
  - redshift: 0.21.1
  - bigquery: 0.21.1
  - snowflake: 0.21.1
  - sqlserver: 0.20.1
```

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
